### ISSUE TITLE
[Impoter] Bug fix on importing inventory using the tooling

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/fhir-tooling#290]
### Context. 
- The Inventory importer script seems to fail in some instances.  This seems to be caused by an addition of multiple references to the `List.subject`
- The subject property can only hold one reference.  

### Acceptance Criteria
- [ ] Correctly map List subjects and entries to avoid such errors.  

### extract info
```cli
Traceback (most recent call last):
  File "/Users/dubdabasoduba/code/ona/server/fhir-tooling/importer/main.py", line 295, in <module>
    main()
  File "/Users/dubdabasoduba/code/ona/virtual-envs/lib/python3.12/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubdabasoduba/code/ona/virtual-envs/lib/python3.12/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/dubdabasoduba/code/ona/virtual-envs/lib/python3.12/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubdabasoduba/code/ona/virtual-envs/lib/python3.12/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubdabasoduba/code/ona/server/fhir-tooling/importer/main.py", line 263, in main
    link_payload = link_to_location(resource_list)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubdabasoduba/code/ona/server/fhir-tooling/importer/importer/builder.py", line 1065, in link_to_location
    return build_assign_payload(arr, "List", "subject=Location/")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dubdabasoduba/code/ona/server/fhir-tooling/importer/importer/builder.py", line 982, in build_assign_payload
    raise ValueError("The number of references should only be 0 or 1")
ValueError: The number of references should only be 0 or 1```

**Comment by Wambere** [comment]
@dubdabasoduba are you able to share the csv or the record or something that can help me recreate this?

**Comment by Wambere** [comment]
@dubdabasoduba the error above is brought by a check in the `build_assign_payload` function [here](https://github.com/onaio/fhir-tooling/blob/089700048f629108510916f7c83da5cab853080b/importer/importer/builder.py#L918)

What it basically tries to do is figure out if we need to create a new List resource or update an existing one by checking how many List resources have the subject = the location resource. For this check we use the url ` https://some-project.smartregister.org/fhir/List/_search?_count=1&subject=Location/some-location-uuid`

If the response has:
- 0 resources: we create a new one
- 1 resource: we update it (adding items to the entry)
- anything else: we throw the error above

Should this be working differently?

**Comment by dubdabasoduba** [comment]
@Wambere  I think it should work the same way but in this case it stopped the whole upload after throwing the error.  Does option 3 _anything else_ mean the server check failed?

**Comment by Wambere** [comment]
Yes, it means multiple List resources were found with the same subject Location
I can update the script to simply log the error and continue. But that would just mean that none of these will be linked to the Location, that part of the process would be skipped

**Comment by dubdabasoduba** [comment]
Let me check the location and figure out why it has two lists.  I think that's a bug either on the web or tooling.

**Comment by pld** [comment]
any update on this?

**Comment by Wambere** [comment]
closing this due to inactivity. The data was cleaned and we've not had any new information or recurrence of the issue
We can always reopen later if necessary
